#undef  FMS_MOS_KIND_
#define FMS_MOS_KIND_ r4_kind

#undef  GET_GRID_CELL_AREA_SG_
#define GET_GRID_CELL_AREA_SG_ get_grid_cell_area_SG_r4

#undef  GET_GRID_COMP_AREA_SG_
#define GET_GRID_COMP_AREA_SG_ get_grid_comp_area_SG_r4

#undef  GET_GRID_CELL_AREA_UG_
#define GET_GRID_CELL_AREA_UG_ get_grid_cell_area_UG_r4

#undef  GET_GRID_COMP_AREA_UG_
#define GET_GRID_COMP_AREA_UG_ get_grid_comp_area_UG_r4

#undef  GET_GRID_CELL_VERTICES_1D_
#define GET_GRID_CELL_VERTICES_1D_ get_grid_cell_vertices_1D_r4

#undef  GET_GRID_CELL_VERTICES_2D_
#define GET_GRID_CELL_VERTICES_2D_ get_grid_cell_vertices_2D_r4

#undef  GET_GRID_CELL_VERTICES_UG_
#define GET_GRID_CELL_VERTICES_UG_ get_grid_cell_vertices_UG_r4

#undef  GET_GRID_CELL_CENTERS_1D_
#define GET_GRID_CELL_CENTERS_1D_ get_grid_cell_centers_1D_r4

#undef  GET_GRID_CELL_CENTERS_2D_
#define GET_GRID_CELL_CENTERS_2D_ get_grid_cell_centers_2D_r4

#undef  GET_GRID_CELL_CENTERS_UG_
#define GET_GRID_CELL_CENTERS_UG_ get_grid_cell_centers_UG_r4

#include <grid2.fh>
