#undef FMS_DIAG_FBU_DATA_TYPE_
#define FMS_DIAG_FBU_DATA_TYPE_ REAL(r4_kind)
#undef FMS_DIAG_FBU_PNAME_
#define FMS_DIAG_FBU_PNAME_ fieldbuff_update_r4
#undef FMS_DIAG_FBCF_PNAME_
#define FMS_DIAG_FBCF_PNAME_ fieldbuff_copy_fieldvals_r4
#undef FMS_DIAG_FBCM_PNAME_
#define FMS_DIAG_FBCM_PNAME_ fieldbuff_copy_misvals_r4
#include <fms_diag_fieldbuff_update.fh>

#undef FMS_DIAG_FBU_DATA_TYPE_
#define FMS_DIAG_FBU_DATA_TYPE_ REAL(r8_kind)
#undef FMS_DIAG_FBU_PNAME_
#define FMS_DIAG_FBU_PNAME_ fieldbuff_update_r8
#undef FMS_DIAG_FBCF_PNAME_
#define FMS_DIAG_FBCF_PNAME_ fieldbuff_copy_fieldvals_r8
#undef FMS_DIAG_FBCM_PNAME_
#define FMS_DIAG_FBCM_PNAME_ fieldbuff_copy_misvals_r8
#include <fms_diag_fieldbuff_update.fh>

#undef FMS_DIAG_FBU_DATA_TYPE_
#define FMS_DIAG_FBU_DATA_TYPE_ INTEGER(i4_kind)
#undef FMS_DIAG_FBU_PNAME_
#define FMS_DIAG_FBU_PNAME_ fieldbuff_update_i4
#undef FMS_DIAG_FBCF_PNAME_
#define FMS_DIAG_FBCF_PNAME_ fieldbuff_copy_fieldvals_i4
#undef FMS_DIAG_FBCM_PNAME_
#define FMS_DIAG_FBCM_PNAME_ fieldbuff_copy_misvals_i4
#include <fms_diag_fieldbuff_update.fh>

#undef FMS_DIAG_FBU_DATA_TYPE_
#define FMS_DIAG_FBU_DATA_TYPE_ INTEGER(i8_kind)
#undef FMS_DIAG_FBU_PNAME_
#define FMS_DIAG_FBU_PNAME_ fieldbuff_update_i8
#undef FMS_DIAG_FBCF_PNAME_
#define FMS_DIAG_FBCF_PNAME_ fieldbuff_copy_fieldvals_i8
#undef FMS_DIAG_FBCM_PNAME_
#define FMS_DIAG_FBCM_PNAME_ fieldbuff_copy_misvals_i8
#include <fms_diag_fieldbuff_update.fh>
