# GNU C
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_C_FLAGS_RELEASE "-O2")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g")

set(CMAKE_C_LINK_FLAGS "")

# ufs flags
set(CMAKE_C_FLAGS_RELEASEUFS "-O3")
set(CMAKE_C_FLAGS_DEBUGUFS "-O0 -g")
