name: Autotools build and unit testing with Intel Classic (weekly)

on:
  schedule:
    - cron: '0 0 * * 0' # sundays @ midnight
  pull_request:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  intel-autotools:
    runs-on: ubuntu-22.04
    env:
      CC: mpiicc
      FC: mpiifort
      CFLAGS:  "-I/libs/include"
      FCFLAGS: "-I/libs/include -g -traceback"
      LDFLAGS: "-L/libs/lib -Wl,-rpath,/libs/lib"
      LD_LIBRARY_PATH: "/libs/lib"
      TEST_VERBOSE: 1
      I_MPI_FABRICS: shm # needed for mpi in image
    steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4.2.0
      with:
        path: /libs
        key: intel-classic-ubuntu22-hdf5-1.14.6-netcdf-4.8.1-yaml-0.2.5-v2
    - name: Install Intel Classic compilers & MPI
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        install-classic: true
        install-oneapi: false
        install-mpi: true
        mpi-wrapper-setup: classic
    - name: Debug Intel compiler environment
      run: |
        set -eux
        echo "PATH=$PATH"
        echo "CC=$CC"
        echo "FC=$FC"
        command -v mpiicc
        command -v mpiifort
        command -v icc
        command -v ifort
        mpiicc -show
        mpiifort -show
        icc --version
        ifort --version
        
    - name: Install packages for building
      run: sudo apt-get update && sudo apt-get install -y autoconf libtool automake zlib1g-dev
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Build netcdf
      run: |
        set -eux
        mkdir -p /libs/include /libs/lib /libs/bin
        chown -R $USER:$USER /libs
        export PATH="/libs/bin:$PATH"
        export LD_LIBRARY_PATH="/libs/lib:${LD_LIBRARY_PATH:-}"
        export CPPFLAGS="-I/libs/include"
        export CFLAGS="-I/libs/include"
        export FCFLAGS="-I/libs/include"
        export LDFLAGS="-L/libs/lib -Wl,-rpath,/libs/lib"
        wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.6/hdf5-1.14.6.tar.gz
        tar xf hdf5-1.14.6.tar.gz && cd hdf5-1.14.6
        CC="$CC" \
        CFLAGS="$CFLAGS" \
        CPPFLAGS="$CPPFLAGS" \
        LDFLAGS="$LDFLAGS" \
        ./configure \
          --prefix=/libs \
          --enable-shared \
          --enable-hl
        make -j install && cd ..
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.8.1.tar.gz
        tar xf v4.8.1.tar.gz && cd netcdf-c-4.8.1
        CC="$CC" \
        FC="$FC" \
        CPPFLAGS="-I/libs/include" \
        CFLAGS="-I/libs/include" \
        FCFLAGS="-I/libs/include" \
        LDFLAGS="-L/libs/lib -Wl,-rpath,/libs/lib" \
        LIBS="-lhdf5_hl -lhdf5 -lz -ldl -lm" \
        ./configure --enable-remote-fortran-bootstrap --prefix=/libs
        make -j install
        make -j -k build-netcdf-fortran
        make -j install-netcdf-fortran
        wget https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz
        tar xf yaml-0.2.5.tar.gz && cd yaml-0.2.5
        ./configure --prefix=/libs
        make -j install
        cd /home/runner/work/FMS/FMS && sudo rm -rf *
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: Configure
      run: |
        set -eux
        export PATH="/libs/bin:$PATH"
        export LD_LIBRARY_PATH="/libs/lib:${LD_LIBRARY_PATH:-}"
        export CPPFLAGS="-I/libs/include"
        export CFLAGS="-I/libs/include"
        export FCFLAGS="-I/libs/include -g -traceback"
        export LDFLAGS="-L/libs/lib -Wl,-rpath,/libs/lib"
        autoreconf -if ./configure.ac
        ./configure --with-yaml
        cat config.log
    - name: Compile
      run:
        set -eux
        export PATH="/libs/bin:$PATH"
        export LD_LIBRARY_PATH="/libs/lib:${LD_LIBRARY_PATH:-}"
        make -j || make
    - name: Run test suite
      run:
        set -eux
        export PATH="/libs/bin:$PATH"
        export LD_LIBRARY_PATH="/libs/lib:${LD_LIBRARY_PATH:-}"
        make check TEST_VERBOSE=1
