name: CMake build and unit tests on MacOS

on: push

jobs:
  # Executables
  build-symmetric:
    runs-on: macOS-latest
    strategy:
      matrix:
        libyaml-flag: [ "", -DWITH_YAML=on ]
        build-type: [ "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_BUILD_TYPE=Debug" ]
    env:
      CMAKE_FLAGS: "${{ matrix.build-type }} ${{ matrix.libyaml-flag }}"
      EXCLUDE_TESTS: "test_mpp_nesting|test_mpp_clock_begin_end_id|test_time_*"
      CC: gcc
      FC: gfortran
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/macos-setup/
      - name: Generate makefiles with CMake
        run: |
          mkdir build
          cd build
          cmake $CMAKE_FLAGS -DUNIT_TESTS=on ..
      - name: Build the library
        run: make -j -C build
      - name: Run the unit tests
        run: cd build && ctest -E "${EXCLUDE_TESTS}" --output-on-failure
